"""added image_url columns

Revision ID: 4bba9e9aed7c
Revises: 9180945a3f0f
Create Date: 2024-09-05 17:46:34.163111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bba9e9aed7c'
down_revision: Union[str, None] = '9180945a3f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('attractions', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('districts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('hotels_and_restaurants', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('provinces', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('transportation', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transportation', 'image_url')
    op.drop_column('provinces', 'image_url')
    op.drop_column('hotels_and_restaurants', 'image_url')
    op.drop_column('districts', 'image_url')
    op.drop_column('categories', 'image_url')
    op.drop_column('attractions', 'image_url')
    op.drop_column('activities', 'image_url')
    # ### end Alembic commands ###
